import { PLANS, decimalAmount } from './catalog.mjs';
import { readyPlan } from './purchase-access.mjs';

export function checkoutPage(config) {
  const { enabled, mode, deliveryReady } = config;
  const sandbox = mode === 'sandbox';
  const options = Object.values(PLANS).filter(plan => readyPlan(plan.key)).map((plan, index) => `<label class="checkout-plan"><input type="radio" name="plan" value="${plan.key}" ${index === 0 ? 'checked' : ''}><span><strong>${plan.name}</strong><span>${plan.accessDays} días de acceso desde el pago</span></span><span class="checkout-price">USD ${decimalAmount(plan.amountCents)}<small>pago único</small></span></label>`).join('');
  const notice = !enabled ? 'VENTAS TODAVÍA CERRADAS · No se iniciará un cobro nuevo. Si ya compraste, puedes consultar tu pago o recuperar tu acceso.' : sandbox ? 'PRUEBA SANDBOX · Usa únicamente una cuenta de prueba de PayPal. No se cobra dinero real.' : 'Compra a YC Systems LLC · Pago único en USD. PayPal te mostrará el importe antes de confirmar.';
  return `<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Pago único | 100 Días — El Método</title><link rel="icon" href="/assets/icon-100-dias.svg"><link rel="stylesheet" href="/assets/checkout.css"><script src="/assets/checkout.js" defer></script></head>
<body><main class="checkout-shell"><a class="checkout-brand" href="/">100 DÍAS <span>EL MÉTODO</span></a><p class="checkout-eyebrow">Contenido digital · Sin cuotas recurrentes</p><h1>Tu plan.<br>Un solo pago.</h1><p class="checkout-intro">Elige el recorrido que quieres comenzar. No necesitas comprar los demás planes. Sin mensualidades, anualidades ni renovación automática.</p>
<p class="checkout-notice" role="status">${notice}</p>
<form id="checkout-form"><fieldset ${enabled ? '' : 'disabled'}><legend>1. Elige tu recorrido</legend>${options}</fieldset><p class="checkout-detail">Incluye prácticas diarias, una prioridad personal, diario guardado y revisiones autoguiadas. Todo es digital: sin sesiones en vivo, asesoría privada ni seguimiento personal. No incluye los paquetes Sistema o Premium ni libros propios adicionales. El acceso empieza al confirmarse el pago y dura 14 o 100 días; no es indefinido.</p>
<label class="checkout-email" for="checkout-email">2. Correo para identificar tu compra</label><input id="checkout-email" name="email" type="email" maxlength="254" autocomplete="email" placeholder="tu@correo.com" required ${enabled ? '' : 'disabled'}>
<div class="checkout-delivery"><h2>Así recibirás el acceso</h2><p>${deliveryReady ? 'Cuando PayPal confirme el pago, verás aquí el botón para entrar y un código privado que debes guardar. Ese código te permite volver desde otro dispositivo; no es una suscripción ni una cuenta con contraseña.' : 'La entrega del programa no está habilitada en esta versión de prueba.'}</p><p>No enviamos un correo automático de acceso. Guarda el código antes de cerrar esta página. No almacenamos datos de tarjetas.</p></div>
<label class="checkout-consent"><input id="checkout-consent" type="checkbox" name="terms" required ${enabled ? '' : 'disabled'}><span>He leído el precio, la duración y la forma de entrega, así como las <a href="/condiciones.html" target="_blank" rel="noopener">condiciones de compra</a> y la <a href="/privacidad.html" target="_blank" rel="noopener">información de privacidad</a>.</span></label>
<button id="checkout-continue" type="submit" ${enabled ? '' : 'disabled'}>${enabled ? (sandbox ? 'Continuar a PayPal de prueba' : 'Continuar a PayPal') : 'Pago aún no disponible'}</button></form>
<div id="paypal-buttons"></div><p id="checkout-state" role="status" aria-live="polite"></p><section id="checkout-access" hidden aria-label="Tu acceso al Método"><h2>Tu acceso está listo</h2><p>Este código es privado. Guárdalo en un lugar seguro; quien lo tenga podrá entrar a tu recorrido y a tus notas.</p><label for="purchase-code">Código de recuperación</label><textarea id="purchase-code" rows="3" readonly spellcheck="false"></textarea><div class="checkout-actions"><button id="save-purchase-code" type="button">Descargar mi código</button><a class="checkout-enter" href="/mi-metodo">Entrar al Método →</a></div></section>
<div id="checkout-recovery" hidden><button id="check-last-order" type="button">Consultar el estado de mi último pago</button><p class="checkout-detail">Si ya aprobaste un pago, consúltalo antes de intentarlo otra vez. Una respuesta perdida no significa que el pago falló.</p></div>
<noscript>Activa JavaScript para pagar con PayPal y recibir tu código de acceso.</noscript><p class="checkout-back"><a href="/mi-metodo">Ya compré: entrar con mi código</a> · <a href="/">Volver al inicio</a></p><p class="checkout-detail">¿Problemas con el pago o el acceso? Escríbenos desde <a href="https://www.instagram.com/100diaselmetodo/" target="_blank" rel="noopener noreferrer">@100diaselmetodo</a>. No envíes contraseñas ni tu código privado por comentarios públicos.</p></main></body></html>`;
}
