import { PLANS, decimalAmount } from './catalog.mjs';

export function checkoutPage(enabled) {
  const options = Object.values(PLANS).map((plan, index) => `<label class="checkout-plan"><input type="radio" name="plan" value="${plan.key}" ${index === 0 ? 'checked' : ''}><span><strong>${plan.name}</strong><span>${plan.accessDays} días de recorrido · digital</span></span><span class="checkout-price">USD ${decimalAmount(plan.amountCents)}<small>pago único</small></span></label>`).join('');
  return `<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Pago único | 100 Días — El Método</title><link rel="icon" href="/assets/icon-100-dias.svg"><link rel="stylesheet" href="/assets/checkout.css"><script src="/assets/checkout.js" defer></script></head>
<body><main class="checkout-shell"><a class="checkout-brand" href="/">100 DÍAS <span>EL MÉTODO</span></a><p class="checkout-eyebrow">Contenido digital · Sin cuotas recurrentes</p><h1>Tu plan.<br>Un solo pago.</h1><p class="checkout-intro">Eliges un plan y pagas su importe una sola vez. No necesitas comprar los demás. Sin mensualidades, anualidades ni renovación automática.</p>
<p class="checkout-notice" role="status">${enabled ? 'PRUEBA SANDBOX · Usa únicamente una cuenta de prueba de PayPal. No se cobra dinero real ni se entrega acceso al programa.' : 'VENTAS TODAVÍA CERRADAS · Estamos preparando la confirmación del pago y la entrega segura. Estos importes no se pueden cobrar desde esta página.'}</p>
<form id="checkout-form"><fieldset><legend>1. Elige el plan</legend>${options}</fieldset><p class="checkout-detail">Todos los planes son autoguiados: sin sesiones en vivo, asesoría privada ni seguimiento personal. Los materiales definitivos están en preparación. El pago único no equivale a acceso indefinido.</p>
<label class="checkout-email" for="checkout-email">2. Correo para identificar la compra de prueba</label><input id="checkout-email" name="email" type="email" maxlength="254" autocomplete="email" placeholder="tu@correo.com" required ${enabled ? '' : 'disabled'}><p class="checkout-detail">El formulario no crea una suscripción. No guardamos datos de tarjetas.</p>
<button id="checkout-continue" type="submit" ${enabled ? '' : 'disabled'}>${enabled ? 'Continuar a PayPal de prueba' : 'Pago aún no disponible'}</button></form>
<div id="paypal-buttons"></div><p id="checkout-state" role="status" aria-live="polite"></p><noscript>Activa JavaScript para usar el checkout de prueba cuando esté habilitado.</noscript><p class="checkout-back"><a href="/">Volver a la muestra y lista de espera</a></p></main></body></html>`;
}
