import test from 'node:test';
import assert from 'node:assert/strict';
import { AREAS, AREA_ORDER, chosenAreas, focusArea, summarizeJourney, paymentSummary, toolPreview, validToolRecord } from './guided-tools.js';
import { validateRecord } from './participant-store.mjs';
import { formatJournalExport } from './participant-tools.js';

const action={area:'profesional',first:'Una frase',second:'Mañana',third:'El título'};
const payment={area:'finanzas',currency:'DOP',rows:[{name:'Servicio',amount:'25.10',date:'2026-09-07'},{name:'Transporte',amount:'10.20',date:'2026-09-06'},{name:'',amount:'',date:''}]};
test('primary area leads a route while existing multi-area selections keep their order',()=>{assert.deepEqual(chosenAreas({}),AREA_ORDER);assert.deepEqual(chosenAreas({lifeArea:'profesional'}),['profesional','mentalidad','finanzas','relaciones','bienestar']);assert.deepEqual(chosenAreas({lifeArea:'finanzas',areas:['relaciones','finanzas']}),['finanzas','relaciones']);assert.deepEqual(chosenAreas({lifeArea:'profesional',areas:['relaciones','finanzas']}),['relaciones','finanzas']);assert.deepEqual([1,2,3,4].map(day=>focusArea(day,{areas:['relaciones','finanzas']})),['relaciones','finanzas','relaciones','finanzas']);});
test('dashboard counts only real daily records, never tools, guide opens or chosen duration',()=>{const s=summarizeJourney([{key:'tool:1:finanzas',body:payment},{key:'day:1',body:{state:'partial'}},{key:'day:2',body:{state:'missed'}},{key:'day:4',body:{state:'complete'}},{key:'day:100',body:{state:'complete'}}],14);assert.deepEqual(s.counts,{complete:1,partial:1,missed:1});assert.equal(s.recorded,3);assert.equal(s.weekRecorded,3);assert.equal(s.next,3);assert.equal(summarizeJourney([],100).recorded,0);});
test('tool validation bounds days, area identity, types, fields and lengths',()=>{assert.ok(validToolRecord('tool:1:profesional',action,14));assert.ok(validateRecord('tool:7:finanzas',payment,14));for(const [key,body]of [['tool:15:profesional',action],['tool:01:profesional',action],['tool:1:mentalidad',action],['tool:1:profesional',{...action,order_id:'OTHER'}],['tool:1:profesional',{...action,first:' '}],['tool:1:profesional',{...action,first:'x'.repeat(1501)}],['tool:1:profesional',{...action,third:[]}],['tool:1:finanzas',{...payment,currency:'BTC'}],['tool:1:finanzas',{...payment,rows:[...payment.rows,payment.rows[0]]}]])assert.equal(validateRecord(key,body,14),null,key);});
test('payment calendar validates dates and decimals without floating point total errors',()=>{assert.equal(paymentSummary(payment.rows).total,35.3);assert.equal(paymentSummary(payment.rows).dated[0].name,'Transporte');for(const amount of ['-1','1e8','NaN','1000000000','12.345','<script>'])assert.equal(validateRecord('tool:1:finanzas',{...payment,rows:[{...payment.rows[0],amount},...payment.rows.slice(1)]},14),null);for(const date of ['2026-02-30','2026-99-01','tomorrow'])assert.equal(validateRecord('tool:1:finanzas',{...payment,rows:[{...payment.rows[0],date},...payment.rows.slice(1)]},14),null);assert.match(toolPreview(payment),/No indica pagos realizados/);});
test('profile supports a visible direction and multiple areas while rejecting invalid values',()=>{const profile={goal:'Mejorar mis rutinas',firstStep:'Elegir un paso',lifeArea:'mentalidad',minutes:10,energy:'steady'};assert.ok(validateRecord('profile',profile,14));assert.ok(validateRecord('profile',{...profile,evidence:'Registrar tres intentos por semana',areas:AREA_ORDER},14));assert.equal(validateRecord('profile',{...profile,evidence:'x'.repeat(501)},14),null);for(const areas of [[],['finanzas','finanzas'],['unknown'],'finanzas'])assert.equal(validateRecord('profile',{...profile,areas},14),null);});
test('exports preserve tool meaning and private entries, never receipt or recovery code',()=>{const text=formatJournalExport({plan:{name:'Alpha'},access:{code:'SECRET'},records:[{key:'tool:2:finanzas',body:payment,updatedAt:'2026-09-04'},{key:'tool:1:profesional',body:action,updatedAt:'2026-09-04'}]});assert.match(text,/Servicio \| 25.10 DOP/);assert.match(text,/Una frase/);assert.ok(text.indexOf('DÍA 1')<text.indexOf('DÍA 2'));assert.doesNotMatch(text,/SECRET/);});
test('text helpers never interpret markup as executable content',()=>{assert.equal(toolPreview({...action,first:'<img src=x onerror=alert(1)>'}).includes('<img src=x onerror=alert(1)>'),true);assert.equal(Object.keys(AREAS).length,5);});
