import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { loadPrelaunchAssets, PRELAUNCH_FILES } from './prelaunch-assets.mjs';

export const SALES_FILES = [...PRELAUNCH_FILES, 'hosting/sales.html', 'hosting/sales.css', 'hosting/participant.html', 'hosting/participant.js', 'hosting/participant-tools.js', 'hosting/participant.css', 'assets/practice-editorial-v2.webp'];
const textAsset = (type, data) => ({ type, encoding: 'utf8', data });
const page = (title, content) => textAsset('text/html; charset=utf-8', `<!doctype html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | 100 Días — El Método</title><link rel="stylesheet" href="/assets/participant.css"></head><body><header class="member-header"><a class="member-brand" href="/">100 <span>DÍAS / EL MÉTODO</span></a><a href="/mi-metodo">Mi recorrido</a></header><main class="member-shell"><article class="panel"><h1>${title}</h1>${content}<p><a href="/">Volver al inicio</a></p></article></main></body></html>`);

export async function loadSalesAssets(root) {
  const assets = await loadPrelaunchAssets(root);
  for (const [file, route, type] of [
    ['sales.html', '/index.html', 'text/html'], ['sales.css', '/assets/sales.css', 'text/css'],
    ['participant.html', '/mi-metodo', 'text/html'], ['participant.js', '/assets/participant.js', 'text/javascript'], ['participant-tools.js', '/assets/participant-tools.js', 'text/javascript'], ['participant.css', '/assets/participant.css', 'text/css'],
  ]) assets[route] = textAsset(type + '; charset=utf-8', await readFile(resolve(root, 'hosting', file), 'utf8'));
  assets['/'] = assets['/index.html'];
  assets['/assets/practice-editorial-v2.webp'] = { type: 'image/webp', encoding: 'base64', data: (await readFile(resolve(root, 'assets/practice-editorial-v2.webp'))).toString('base64') };
  assets['/robots.txt'] = textAsset('text/plain; charset=utf-8', 'User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /mi-metodo\nDisallow: /comprar\n');
  assets['/404.html'] = page('No encontramos esa página', '<p>Vuelve al inicio para ver los recorridos o entra con tu código desde «Mi recorrido».</p>');
  assets['/condiciones.html'] = page('Compra y entrega', `<p>Oferta de YC Systems LLC para 100 Días — El Método. Actualizada el 3 de septiembre de 2026.</p><h2>Qué compras</h2><p>Acceso Alpha: USD 9, pago único, prácticas de los días 1 al 14 y 14 días de acceso. El Método: USD 29, pago único, prácticas de los días 1 al 100 y 100 días de acceso. Ambos incluyen una prioridad inicial, registro de prácticas, revisiones autoguiadas y descarga de tus propios registros. No hay mensualidades, anualidades ni renovación automática.</p><p>Son recorridos digitales autoguiados: no incluyen productos físicos, sesiones en vivo, asesoría privada, libros propios adicionales ni una garantía de resultados. Sistema (USD 79) y Premium (USD 297) no se venden en esta versión.</p><h2>Pago, duración y acceso</h2><p>PayPal procesa el pago en USD a favor de YC Systems LLC. Revisa el importe y cualquier conversión de moneda que PayPal te muestre antes de autorizar. El acceso comienza cuando el pago queda confirmado; una operación pendiente no concede acceso. Cada recorrido dura 14 o 100 días consecutivos desde esa confirmación. No es un acceso indefinido y las pausas no amplían su duración.</p><p>Recibirás en esta web un botón de entrada y un código privado de recuperación. No se envía un correo automático de acceso. Guarda el código antes de cerrar la página; permite entrar desde otro dispositivo. Necesitas navegador, JavaScript, cookies esenciales y conexión a internet. No necesitas una cuenta de ChatGPT.</p><p>No compartas el código: da acceso a tu contenido y a tus registros. Un identificador de transacción o un correo electrónico no sustituyen ese código. Puedes descargar tus registros antes de que venza el acceso.</p><h2>Asistencia y solicitudes de devolución</h2><p>Para problemas con el acceso, un cobro o una solicitud de devolución, contacta por mensaje privado con <a href="https://www.instagram.com/100diaselmetodo/" target="_blank" rel="noopener noreferrer">@100diaselmetodo</a>, la cuenta oficial del proyecto. Facilita la referencia de compra y describe el problema. No publiques contraseñas, códigos privados ni datos de tarjetas. Verificaremos la compra antes de intervenir; no se promete una respuesta o devolución inmediata.</p><p>El acceso deja de estar activo si PayPal confirma un reembolso o revierte la operación; una devolución parcial queda pendiente de revisión. Estas condiciones no pretenden limitar los derechos obligatorios que resulten aplicables a tu compra.</p><h2>Uso del contenido</h2><p>Las prácticas son educativas. No sustituyen atención médica, terapia, asesoría financiera ni otros servicios profesionales. Las reflexiones adaptadas no se presentan como citas textuales. Los recursos externos opcionales pertenecen a sus autores y se consultan bajo las condiciones de sus plataformas.</p>`);
  assets['/privacidad.html'] = page('Información de privacidad', `<p>YC Systems LLC gestiona este proyecto y los datos que decides aportar. Información actualizada el 3 de septiembre de 2026.</p><h2>Compras y recorrido</h2><p>Guardamos el correo indicado al comprar, el plan, el importe y la moneda, referencias de pedido y captura de PayPal, el estado del pago y las fechas necesarias para comprobar la compra y la duración del acceso. PayPal procesa el medio de pago: esta web no guarda tarjetas ni tu contraseña de PayPal.</p><p>Cuando pulsas Guardar, almacenamos en el servidor tu prioridad, el ritmo elegido, el texto de tus registros y revisiones, su versión y la fecha de actualización, asociados a tu compra. Necesitamos estos datos para recuperar el recorrido entre dispositivos. No introduzcas información médica, números de cuenta, contraseñas ni datos privados de otras personas.</p><h2>Cookies y código de acceso</h2><p>Usamos cookies esenciales y privadas del navegador para asociar tu sesión a la compra y comprobar tu acceso. Se conserva localmente la referencia de tu último pedido para consultar su estado; esa referencia no concede acceso. El código privado permite entrar a tu recorrido y a tus notas: guárdalo de forma segura y no lo compartas.</p><p>Para limitar abusos guardamos contadores técnicos con un identificador protegido derivado de la dirección de conexión, no la IP en texto. Los contadores antiguos se eliminan de manera gradual. El proveedor de alojamiento puede procesar información técnica necesaria para prestar y proteger el servicio.</p><h2>Lista de novedades y métricas</h2><p>Si te registraste en la lista de espera, conservamos tu correo, nombre opcional, interés y consentimiento para las comunicaciones que solicitaste. No usamos el correo de compra como consentimiento automático de marketing. Contamos visitas y procedencia de campañas sin cookies publicitarias ni incluir tus notas o datos de compra en esos eventos.</p><h2>Proveedores y solicitudes</h2><p>El alojamiento y la base de datos del proyecto prestan el servicio técnico; PayPal recibe los datos necesarios para procesar los pagos. Al seguir enlaces a Instagram, Facebook, YouTube u otros recursos, se aplican las políticas de esas plataformas. No enviamos tus notas a esos enlaces ni las usamos para anuncios.</p><p>Puedes descargar tus registros desde el recorrido mientras el acceso esté activo y solicitar información, corrección o eliminación por mensaje privado a <a href="https://www.instagram.com/100diaselmetodo/" target="_blank" rel="noopener noreferrer">@100diaselmetodo</a>. Verificaremos que la solicitud corresponde a tu compra. Los registros necesarios para justificar una transacción o atender obligaciones aplicables pueden conservarse aunque se eliminen las notas del recorrido. El vencimiento del acceso no borra automáticamente los registros.</p>`);
  return assets;
}
